package frc.robot.lib;

/**
 * The following class exists to stop crashes at runtime trying to access missing/mistyped
 * pathweaver files (#145). This class is autogenerated at compile, containing public strings for
 * all of the files in the pathweaver output directory. These public strings are to be used with
 * driveRelativeWaypoints(pathname) in Auto.java instead of directly referring to the pathweaver
 * files.
 */
public class AutoPaths {

    // DO NOT CHANGE THIS FILE!
    // THIS ENTIRE FILE WILL BE REGENERATED BY GRADLE AT COMPILE TIME!
    public static final String k5ballOpponent1 = "5ball_opponent_1.wpilib.json";
    public static final String k5ballOpponent2 = "5ball_opponent_2.wpilib.json";
    public static final String kBarrelRacing = "barrelRacing.wpilib.json";
    public static final String kBounce0 = "bounce_0.wpilib.json";
    public static final String kBounce1 = "bounce_1.wpilib.json";
    public static final String kBounce2 = "bounce_2.wpilib.json";
    public static final String kBounce3 = "bounce_3.wpilib.json";
    public static final String kToBalls = "toBalls.wpilib.json";
    public static final String kToGoal = "toGoal.wpilib.json";
    public static final String kToStart = "toStart.wpilib.json";

}
